name: Build, Test and Lint check

on:
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Use Node.js v24.15.0
        uses: actions/setup-node@v5
        with:
          node-version: 24.15.0
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Check linting
        run: npm run lint
